"""F9 regression corpus: (id, text, expected) with expected in {"green","red"}. Rules-only AND live pipeline are evaluated against it."""
G, R = "green", "red"
CORPUS = [
 # ---- telco / recharge (GREEN)
 ("jio_success", "Recharge of Rs 299 successful on 9876543210. Validity 28 days, 1.5GB/day, unlimited calls. Thank you for choosing Jio. Track on https://www.jio.com/selfcare", G),
 ("jio_offer", "Jio: Unlimited 5G data with Rs 349 plan. Validity 28 days. Offer expires 31 Oct. Recharge now on MyJio app or https://www.jio.com", G),
 ("airtel_plan", "Airtel Thanks: Get 2GB/day + unlimited calls with Rs 479 plan, validity 56 days. Recharge now at https://www.airtel.in/prepaid-recharge", G),
 ("vi_offer", "Vi: Enjoy double data this weekend on Rs 299 pack! Offer ends Sunday. Recharge at https://www.myvi.in/recharge", G),
 ("airtel_expiry", "Dear customer, your Airtel pack expires tomorrow. Recharge to continue enjoying uninterrupted services. Recharge on Airtel Thanks app or https://www.airtel.in", G),
 ("jio_expiry", "Your Jio plan validity ends today. Recharge now to continue unlimited 5G. https://www.jio.com/recharge", G),
 ("vi_success", "Rs 199 recharge successful for 98xxxxx210. Balance Rs 12.50. Data 1GB/day valid till 12-Nov. Vi", G),
 ("airtel_hi", "एयरटेल: 299 रुपये के रिचार्ज पर 28 दिन की वैधता, रोज़ 1.5GB डेटा और अनलिमिटेड कॉल। अभी रिचार्ज करें https://www.airtel.in", G),
 ("jio_gu", "જિયો: ₹299 ના રિચાર્જ પર 28 દિવસની વેલિડિટી, દરરોજ 1.5GB ડેટા. હમણાં રિચાર્જ કરો https://www.jio.com", G),
 ("bsnl_plan", "BSNL: Plan voucher Rs 107 validity 35 days, 3GB data. Recharge via https://www.bsnl.in or BSNL Selfcare app.", G),
 ("hinglish_recharge", "Aapka Rs 239 ka recharge safal raha. Validity 24 din. Jio ka dhanyawad. Details: https://www.jio.com", G),
 # ---- OTP notices with do-not-share (GREEN)
 ("otp_en", "123456 is your OTP for login. Do not share it with anyone. -SBI", G),
 ("otp_en2", "Your OTP is 654321. Never share your OTP, PIN or password with anyone, including bank staff.", G),
 ("otp_hi", "आपका OTP 482913 है। इसे किसी को न बताएं। बैंक कभी OTP नहीं मांगता।", G),
 ("otp_hi2", "ओटीपी 553311 है। कृपया इसे किसी के साथ साझा न करें।", G),
 ("otp_gu", "તમારો OTP 771122 છે. આ OTP કોઈને શેર ન કરો.", G),
 ("otp_hinglish", "Aapka OTP 908172 hai. Ise kisi ke saath share na karein. Bank kabhi OTP nahi maangta.", G),
 ("otp_hinglish2", "OTP 112233 hai. Kisi ko mat batayein, SBI staff bhi nahi poochhta.", G),
 ("otp_txn", "OTP for txn of Rs 1,500.00 at AMAZON is 445566. Do not share this OTP with anyone. Bank never asks for OTP.", G),
 ("otp_hdfc", "123456 is the OTP for your HDFC Bank NetBanking. Valid for 10 minutes. Do not disclose it to anyone.", G),
 # ---- bank / UPI / EMI / bills / delivery (GREEN)
 ("debit_alert", "Rs 2,300.00 debited from A/c XX4821 on 02-Oct-26 to VPA swiggy@icici. UPI Ref 628391847562. Not you? Call 1800-1234 -HDFC Bank", G),
 ("credit_alert", "Rs 15,000 credited to your A/c XX1122 on 03-Oct by NEFT from ACME PVT LTD. Avl Bal Rs 48,210.55 -SBI", G),
 ("upi_sent", "You have sent Rs 450 to RAMESH KUMAR via Google Pay. UPI transaction ID 429384756291.", G),
 ("emi_due", "Dear customer, your EMI of Rs 4,520 for loan A/c XX9087 is due on 05-Oct. Please maintain sufficient balance. -ICICI Bank", G),
 ("cc_due", "Your HDFC credit card ending 1234 statement is generated. Total due Rs 8,450, minimum due Rs 420, due date 15-Oct. Pay via https://www.hdfcbank.com or NetBanking.", G),
 ("loan_emi_nothreat", "Reminder: your loan EMI of Rs 3,200 is due tomorrow. Kindly pay on time via the bank app to avoid late fees. -Axis Bank", G),
 ("amazon_deliv", "Your Amazon order #405-1234567 is out for delivery today. Share OTP 4821 with the delivery agent only at the time of delivery. Track: https://www.amazon.in/orders", G),
 ("flipkart_deliv", "Flipkart: Your order will be delivered today. Delivery OTP is 7391. Please share this OTP with the delivery partner only on delivery. Do not share it over phone or SMS.", G),
 ("delhivery", "Delhivery: Your shipment AWB 1234567890 is out for delivery. Delivery partner Suresh 9876543210 will call you.", G),
 ("electricity", "Dear consumer, your electricity bill of Rs 1,245 for Sept is generated. Due date 12-Oct. Pay at https://www.torrentpower.com or your app.", G),
 ("gas_bill", "Your piped gas bill of Rs 680 is due on 10-Oct. Pay online to avoid late fee. -IGL", G),
 ("water_bill", "Water bill for consumer 10231 is Rs 340, last date 20-Oct. Pay on the municipal portal.", G),
 ("irctc", "PNR 2345678901: Your ticket is confirmed. Train 12951 Mumbai Central to New Delhi on 10-Oct, Coach B2, Seat 34. -IRCTC https://www.irctc.co.in", G),
 ("appointment", "Reminder: your appointment with Dr. Mehta is tomorrow at 5 PM at City Clinic. Reply YES to confirm.", G),
 ("bank_upi_aware", "SBI: Never share your UPI PIN or OTP with anyone. Beware of fraud calls. Report fraud on 1930.", G),
 ("friend_video", "Hey, can you send me the video from yesterday's party? Thanks!", G),
 ("job_offer", "Congratulations! We are pleased to offer you the role of Software Engineer at Acme Corp. Please review the offer letter and reply by Friday.", G),
 ("hi_bank_debit", "आपके खाते XX4821 से ₹2,300 डेबिट हुए। शेष राशि ₹10,200। -एसबीआई", G),
 ("gu_bank_credit", "તમારા ખાતા XX1122 માં ₹5,000 જમા થયા. બાકી રકમ ₹20,400. -બેંક ઓફ બરોડા", G),
 # ---- OTP-asking scams (RED)
 ("otp_exec", "Your OTP is 123456, share it with our executive to cancel the transaction.", R),
 ("otp_officer", "Sir, I am calling from bank. Please tell me the OTP sent to your phone to stop the fraud transaction.", R),
 ("otp_sbi_verify", "OTP for SBI, please share to verify your account.", R),
 ("otp_customer_care", "Share the OTP you received with our customer care agent to avoid account block.", R),
 ("otp_send_number", "Send the OTP to 9876543210 to get your refund.", R),
 ("otp_caller", "Please give the OTP to the caller to confirm your identity, else your card will be blocked.", R),
 ("otp_hinglish1", "Aapko ek OTP aaya hoga, OTP bata do warna account block ho jayega.", R),
 ("otp_hinglish2", "Refund ke liye OTP share kariye abhi, nahi to cancel ho jayega.", R),
 ("otp_hi_scam", "आपके खाते की जाँच के लिए अभी ओटीपी बताएं, वरना खाता बंद हो जाएगा।", R),
 ("otp_hi_exec", "बैंक अधिकारी को अपना ओटीपी बताइए ताकि ट्रांज़ैक्शन कैंसल हो सके।", R),
 ("otp_gu_scam", "તમારું ખાતું બ્લોક થશે. હમણાં ઓટીપી જણાવો.", R),
 ("otp_gu_share", "ટ્રાન્ઝેક્શન રદ કરવા માટે બેંક અધિકારીને ઓટીપી શેર કરો.", R),
 ("otp_tell_me", "Tell me the OTP that just came to you, I am from SBI.", R),
 ("otp_pin_agent", "Your UPI PIN is needed to verify. Share the PIN with the agent.", R),
 # ---- existing scam families (RED)
 ("kyc", "Your KYC is pending, account blocked today. Update: http://bit.ly/x1", R),
 ("collect", "Approve the collect request of Rs 5000 and enter your UPI PIN to receive the refund.", R),
 ("courier", "Your parcel is held at customs. Pay Rs 49 redelivery fee at http://india-post-fee.xyz to release it.", R),
 ("lottery", "Congratulations! You won Rs 25,00,000 in the KBC lucky draw. Call 9876543210 and pay Rs 5000 processing fee.", R),
 ("digital_arrest", "This is CBI. A parcel in your name contains drugs. You are under digital arrest. Do not disconnect the call.", R),
 ("lookalike_jio", "Jio: your plan expires today! Recharge now at http://jio-recharge.xyz to avoid disconnection.", R),
 ("lookalike_sbi", "SBI: your account is blocked. Update details at https://sbi-kyc.top now.", R),
 ("official_with_otp_ask", "Visit https://www.sbi.co.in and share your OTP with our executive to complete verification.", R),
]
